CREATE TABLE IF NOT EXISTS users (
    name VARCHAR(255),
    age INT,
    id INT NOT NULL AUTO_INCREMENT
);

CREATE TABLE IF NOT EXISTS products (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255),
    price DECIMAL(10,2)
);

